clear; clc; close all;

A = TBW.ADP( ...
    'Name', "Config A", ...
    'Span', 64.0, ...
    'WingArea', 341.33, ...
    'AR', 12.0, ...
    'Taper', 0.28, ...
    'MTOM', 280000, ...
    'HasStrut', false, ...
    'LoadFactor', 2.5);

B = TBW.ADP( ...
    'Name', "Config B", ...
    'Span', 70.0, ...
    'WingArea', 350, ...
    'AR', 14.0, ...
    'Taper', 0.35, ...
    'MTOM', 280000, ...
    'HasStrut', true, ...
    'StrutAttachY', 0.45*(70/2), ...
    'StrutShare', 0.25, ...
    'LoadFactor', 2.5);

[GeomA, MassA] = TBW.BuildGeometry(A);
[GeomB, MassB] = TBW.BuildGeometry(B);

RA = TBW.StructuralAnalysis(A);
RB = TBW.StructuralAnalysis(B);

fprintf('A root BM = %.3f MNm\n', RA.RootBM_Nm/1e6);
fprintf('B root BM = %.3f MNm\n', RB.RootBM_Nm/1e6);

figure(1); clf;
plot(RA.y, RA.M/1e6, 'LineWidth', 1.8); hold on;
plot(RB.y, RB.M/1e6, 'LineWidth', 1.8);
grid on;
xlabel('y [m]');
ylabel('Bending moment [MNm]');
legend('Config A','Config B','Location','best');
title('TBW namespace: bending comparison');

figure(2); clf;
cast.draw(GeomA, MassA); hold on;
axis equal;
xlim([0 65]);
ylim([-40 40]);
grid on;
title('Config A geometry');

figure(3); clf;
cast.draw(GeomB, MassB); hold on;
axis equal;
xlim([0 65]);
ylim([-40 40]);
grid on;
title('Config B geometry');